### PR TITLE
Make the property AutoAcknowledge available to be changed, and added function to stop consumers.

### LINKED ISSUE #23: Missing method to override ConsumerAutoAck
There is no current method to change the consumer options `ConsumerAutoAck`

### PR DESCRIPTION
**Pull request by victorct-pronto**
Fixes #23 and #24

### CODE REVIEW

**Comment by wagslane** [comment]
Something failing here - please check the tests

**Comment by wagslane** [comment]
Also, if you make separate PRs for each issue it will be easier to approve them one at a time

**Comment by victorct-pronto** [comment]
@wagslane Fixed the testing: 
image

Also I deleted the other branch, so that's why I pushed both commits at the same time,  if that's a problem I can recreate the branch with the other code, it's not that much.

**Comment by victorct-pronto** [comment]
@wagslane any update?

**Pull request merged**
