### PR TITLE
Remove deprecated 'Publish' method

### PR DESCRIPTION
**Pull request by aaqaishtyaq**
This PR adds `PublishWithContext` for publishing to Rabbitmq.

As a requirement, `github.com/rabbitmq/amqp091-go` needs to be updated.
Removed `vendor` directory, in favor of `go mod download`

Fixes: #90

### CODE REVIEW

**Comment by aaqaishtyaq** [comment]
@wagslane Please review.

**Comment by aaqaishtyaq** [comment]
Ideally it should be a different method. `Publish` is deprecated but it is not removed. 

From the perspective of this library. User should not worry about different ways to `Publish`. It should be just one method to remove ambiguity. 
Rabbitmq does not want to break their current API but we have already changed our API. IMO, We can accommodate this as part of current Publish method (Create a new release with major version change). 

If you think we should have a separate method for `PublishWithContext` then I can update the PR.

**Comment by wagslane** [comment]
Yeah, I think it would be best to have two separate functions!

**Comment by pwli0755** [comment]
any updates on this thread?  I really need this Context intergration in my tracing scenarios.
I personally prefer add the `WithContext`  approach and leave old API as  deprecated.

**Comment by aaqaishtyaq** [comment]
@wagslane, Please review. 

I had to update examples because the static-check was failing due to the usage of the deprecated `Publish` method.

**Comment by bpartov-tc** [comment]
I am interested in this pull request as well, is this branch being merged any time soon?

**Review by wagslane — APPROVED** [review]

**Pull request merged**
