### PR TITLE
Declare process for Publisher | Part 2

### PR DESCRIPTION
**Pull request by h44z**
Split #80  into two parts. This part contains:

- declaration of queues, exchanges and bindings is also possible if the Publisher is used (#43 )
- updated examples

### CODE REVIEW

**Comment by wagslane** [comment]
My issue with this one is that it doesn't seem right to me that a publisher would declare a queue - those 2 concepts should be decoupled in most applications

**Comment by h44z** [comment]
@wagslane this decision should be made by the application developer, not the api. If someone wants or needs to declare queues or whatever as publisher, this should be supported by the api.

**Comment by wagslane** [comment]
Fyi we now have some conflicts here. I'll review once those are resolved

**Comment by wagslane** [comment]
I actually made these updates and merged them. Well, accomplishes the same thing but is done slightly differently. Thanks!

**Pull request closed without merging**
