### PR TITLE
fix startNotifyFlowHandler (issue #13)

### PR DESCRIPTION
**Pull request by pwli0755**
fix issue #13 
and add some comment

### CODE REVIEW

**Comment by wagslane** [comment]
Please fix tests!

**Comment by pwli0755** [comment]
```shell
go test ./...
?   	github.com/wagslane/go-rabbitmq	[no test files]
?   	github.com/wagslane/go-rabbitmq/examples/consumer	[no test files]
?   	github.com/wagslane/go-rabbitmq/examples/logger	[no test files]
?   	github.com/wagslane/go-rabbitmq/examples/publisher	[no test files]
go list -f '{{.Dir}}' ./... | grep -v /vendor/ | xargs -L1 gofmt -l
/home/runner/work/go-rabbitmq/go-rabbitmq/consume_options.go
test -z $(go list -f '{{.Dir}}' ./... | grep -v /vendor/ | xargs -L1 gofmt -l)
make: *** [Makefile:8: fmt] Error 1
Error: Process completed with exit code 2.
```
emm, it seems this error was triggered by `consume_options.go`

BTW, I'd like to suggest migrate to  golangci-lint to check codebase.

**Comment by wagslane** [comment]
My bad! Just pull the latest changes and you should be good

**Comment by pwli0755** [comment]
> My bad! Just pull the latest changes and you should be good

done! pls have a check

**Pull request merged**
