### PR TITLE
update: Add manual action to consumer handler & expose function for Publishing with deferred confirmation

### PR DESCRIPTION
**Pull request by vishal-android-freak**
I would want to spin up goroutines to do some other processing on the message and use the amqp.Delivery object to send acknowledgements later from the routine. Currently the consumer handler expects a compulsory type which doesn't let us do any processing from a routine.

### CODE REVIEW

**Comment by wagslane** [comment]
Please re-pull to trigger a new CI flow! Thanks

**Comment by vishal-android-freak** [comment]
@wagslane done!

**Comment by vishal-android-freak** [comment]
Exposed the function from the base amqp llibrary to publish with deferred confirms. This is useful in correlating published messages with publisher confirms via `NotifyPublish()`

**Comment by vishal-android-freak** [comment]
@wagslane sorry, you must be busy, but does this look good to merge? Wanted to switch our dependency from our fork to this main repo. Would be great if you can get it merged

**Review by wagslane — APPROVED** [review]

**Pull request merged**
