### PR TITLE
Replace logger with a Logger interface to allow for custom loggers.

### PR DESCRIPTION
**Pull request by tomarus**
Hey, great project! I'm using streadway/amqp a lot and this project basically takes away a lot of pain :)

In order to test this a bit I needed a custom logger so I swapped the logger struct with a Logger interface. I've also replaced some log.Println() with just log.Printf() and added some logging around Ack and Nack.

It should be backwards compatible and I even added an example.

Let me know what you think, I've only tested this in my local setup. Thank you.

### CODE REVIEW

**Comment by wagslane** [comment]
Hey, thanks for opening a PR! This is a great idea, I'm worried about using a new logger when there is already a standard though. Would you mind updating your PR to use the standard logging interface rather than creating a new one?

https://golang.org/pkg/log/#Logger

**Comment by tomarus** [comment]
Hey thanks for your reply, but I don't think this is really the same (but I might be wrong). There is no standard logging interface in the Go and I think you are referring to the Go logger type. My Logger interface allows any struct with a Printf() method to be the logger, and the default Go log type is the thing I try to not use :)

**Comment by wagslane** [comment]
You're totally right, sorry I got my wires crossed. I'll merge this in.

**Comment by tomarus** [comment]
Ai thanks man, logging can be a pain for sure :)

**Pull request merged**
